In [1]:
#create a numpy array
import numpy 
arr=numpy.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
#importing numpy using alias
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
import numpy as np
arr=np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
import numpy as np
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
import numpy as np
arr=np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [25]:
import numpy as np
arange_arr=np.arange(0,10,2)
print(arange_arr)

[0 2 4 6 8]


In [31]:
import numpy as np
linspace_arr=np.linspace(0,1,5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [35]:
import numpy as np
arr_int=np.array([1,2,3],dtype=np.int64)
arr_float=np.array([1,2,3],dtype=np.float64)
print("Interge Array:",arr_int)
print("Float Array:",arr_float)

Interge Array: [1 2 3]
Float Array: [1. 2. 3.]


In [37]:
#create a 0-D array
arr=np.array(4)
print(arr)

4


In [39]:
#create a 1-D array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [53]:
#create a 2-D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [55]:
#create a 3-D array
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [57]:
#create a 10 Dimension array
arr=np.array([1,2,3,4,5],ndmin=10)
print(arr)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


In [59]:
#check number of dimension in each array
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [61]:
#get the shape and s=dimension  of 2d array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)

(2, 4)
2


In [63]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array is of Type:",type(arr))
print("No of Dimensions:",arr.ndim)
print("Shape of Array:",arr.shape)
print("Size of Array:",arr.size)
print("Array stores elements of type:",arr.dtype)

Array is of Type: <class 'numpy.ndarray'>
No of Dimensions: 2
Shape of Array: (2, 3)
Size of Array: 6
Array stores elements of type: int32


In [65]:
# Reshaping a 1d array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [67]:
# Reshaping a 1d array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
