In [1]:
# Filter 1st and 3rd item
import numpy as np
a=np.array([1,2,3,4])
x=[True,False,True,False]
b=a[x]
print(b)


[1 3]


In [3]:
arr=np.array([11,2,23,24,18,1,27,56])
filter_arr= arr > 20
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False  True  True False False  True  True]
[21 23 44 27 56]


In [7]:
arr=np.array([21,2,23,24,29,19])
filter_arr=[]
for element in arr:
    if element>20:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[True, False, True, True, True, False]
[21 23 24 29]


In [9]:
#gernerate random number
from numpy import random
x=random.randint(100)
print(x)

23


In [11]:
from numpy import random
x=random.rand()
print(x)

0.547141157926119


In [13]:
#generate 1d array containing 5 random interger from 0 to 100
from numpy import random
x=random.randint(100,size=5)
print(x)

[48 22 14 67 70]


In [15]:
#generate 2d array containing 3rows and each contain 5  random interger from 0 to 100
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[43  4 32 36 52]
 [79 96 94 82 89]
 [79 34 82 31 27]]


In [19]:
#generate 3d array containing 3rows and each contain 5  random interger from 0 to 100
from numpy import random
x=random.randint(100,size=(2,3,5))
print(x)

[[[82 42 88  0 87]
  [26 98 72 27 17]
  [35 73 29  0 88]]

 [[24 53 18 67 66]
  [63 33 91 57 34]
  [85 77 67 72 48]]]


In [21]:
#use ramdom choice and make an array
from numpy import random
x=random.choice([3,5,7,9],size=(3,5))
print(x)

[[5 7 9 5 5]
 [7 3 3 5 5]
 [9 7 3 5 9]]


In [23]:
#use ramdom choice and make an array
# using probality
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(2,5))
print(x)

[[7 5 7 7 7]
 [5 7 7 5 7]]


In [25]:
#use ramdom choice and make an array shuffle
from numpy import random
arr=np.array([11,2,30,4,5])
random.shuffle(arr)
print(arr)

[ 4  2  5 30 11]


In [27]:
from numpy import random
arr=np.array([11,2,30,4,5])
print(random.permutation(arr))

[ 2 30  5 11  4]
