In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
total_sum=np.sum(arr)
print("Sum of all elements:",total_sum)
axis0_sum=np.sum(arr,axis=0)#sum along column
print("Sum along axis 0:",axis0_sum)
axis1_sum=np.sum(arr,axis=1)#sum along rows
print("Sum along axis 1:",axis1_sum)

Sum of all elements: 21
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [6]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
total_sum=np.sum(arr)
print("Sum of all elements:",total_sum)
axis0_sum=np.sum(arr,axis=0)#sum along column
print("Sum along axis 0:",axis0_sum)
axis1_sum=np.sum(arr,axis=1)#sum along rows
print("Sum along axis 1:",axis1_sum)

Sum of all elements: 78
Sum along axis 0: [[ 8 10 12]
 [14 16 18]]
Sum along axis 1: [[ 5  7  9]
 [17 19 21]]


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
mean_value=np.mean(arr)
print("Mean of all elements:",mean_value)
axis0_mean=np.mean(arr,axis=0)#mean along column
print("Mean along axis 0:",axis0_mean)
axis1_mean=np.mean(arr,axis=1)#sum along rows
print("Sum along axis 1:",axis1_mean)

Mean of all elements: 3.5
Mean along axis 0: [2.5 3.5 4.5]
Sum along axis 1: [2. 5.]


In [12]:
a=np.array([1,2,2,3,3,3,4,4,5,5])
median_value=np.median(a)
print("Median:",median_value)

Median: 3.0


In [16]:
a=np.array([[1,2,2,3,3,3,4,4,5,5]])
median_value=np.median(a)
print("Median:",median_value)
median_value0=np.median(a,axis=0)#column 
print("Median:",median_value0)
median_value1=np.median(a,axis=1)#rows
print("Median:",median_value1)

Median: 3.0
Median: [1. 2. 2. 3. 3. 3. 4. 4. 5. 5.]
Median: [3.]


In [18]:
a=np.array([10,8,8,6])
#calculate varience
print(a)
print(np.mean(a))
print(np.var(a))

[10  8  8  6]
8.0
2.0


In [20]:
a=np.array([10,8,8,6])
#calculate varience
print(a)
print(np.mean(a))
print(np.var(a))
print(np.std(a))#standard daviation

[10  8  8  6]
8.0
2.0
1.4142135623730951


In [1]:
import numpy as np 
a=np.array([1,2,3,4,5])
weights=np.array([0.1,0.2,0.3,0.2,0.2])
weighted_avg=np.average(a,weights=weights)
print("Array",a)
print("Weights",weights)
print("Weighted Average",weighted_avg)

Array [1 2 3 4 5]
Weights [0.1 0.2 0.3 0.2 0.2]
Weighted Average 3.2


In [3]:
a=np.array([1,8,3,4,2,7,10])
range_of_values=np.ptp(a)
print("Array",a)
print("Range of Values(max-min):",range_of_values)

Array [ 1  8  3  4  2  7 10]
Range of Values(max-min): 9


In [7]:
# PErcentile in 1d array
a=np.array([1,2,3,4,5,6,7,8,9,10])
#define the percentile
percentile_value=40
percentile_result=np.percentile(a,percentile_value)
print(a)
print(percentile_result)

[ 1  2  3  4  5  6  7  8  9 10]
4.6


In [11]:
#product
a=np.array([[1,2,3],[4,5,6]])
prod_axis0=np.prod(a,axis=0)
print("Product along axis 0:",prod_axis0)
prod_axis1=np.prod(a,axis=1)
print("Product along axis 1:",prod_axis1)


Product along axis 0: [ 4 10 18]
Product along axis 1: [  6 120]


In [13]:
#cumutative product
a=np.array([1,2,3,4,5])
cumulative_prod=np.cumprod(a)
print("Cumulative Product:",cumulative_prod)

Cumulative Product: [  1   2   6  24 120]


In [15]:
#cumutative product 2d
a=np.array([[1,2,3],[4,5,6]])
cumulative_prod=np.cumprod(a)
print("Cumulative Product:",cumulative_prod)
cumulative_prod0=np.cumprod(a,axis=0)
print("Cumulative Product in Axis=0:\n",cumulative_prod0)
cumulative_prod1=np.cumprod(a,axis=1)
print("Cumulative Product in Axis=1:\n",cumulative_prod1)

Cumulative Product: [  1   2   6  24 120 720]
Cumulative Product in Axis=0:
 [[ 1  2  3]
 [ 4 10 18]]
Cumulative Product in Axis=1:
 [[  1   2   6]
 [  4  20 120]]


In [19]:
#mode
import scipy
from scipy import stats
a=np.array([1,2,2,3,3,3,4,4,5,6,6,7,7,7,7,7,8])
mode_result=stats.mode(a)
print("Array",a)
print("Mode",mode_result)

Array [1 2 2 3 3 3 4 4 5 6 6 7 7 7 7 7 8]
Mode ModeResult(mode=7, count=5)
