In [1]:
#print only 2 and 3rd element
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:3])

[2 3]


In [3]:
a=np.array([1,2,3,4,5,6,7])
print(a[3:])
print(a[3:7])
print(a[-4:])

[4 5 6 7]
[4 5 6 7]
[4 5 6 7]


In [15]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0,1:2])

[2]


In [13]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:2])

[7]


In [17]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:2])

[[2]
 [7]]


In [71]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#print2
print(a[0,0,1:2])
print(a[0,1,1:2])
print(a[1,0,1:2])
print(a[1,1,1:2])
print(a[0,0:2,1:2])
#print 2 & 8
print(a[0:2,0,1:2])
# print 2,5,8,11
print(a[0:2,0:2,1:2])

[2]
[5]
[8]
[11]
[[2]
 [5]]
[[2]
 [8]]
[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]


In [73]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#to get first element in 1st array
print(a[0,1])
#to get first element in 2nd array
print(a[1,1])
#to get first element in 1st array
print(a[:,1])

2
7
[2 7]


In [79]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[0,1,1])
print(a[1,1,1])
print(a[0,0,1])
print(a[1,0,1])
print(a[:,0,1])
print(a[:,:,1])


5
11
2
8
[2 8]
[[ 2  5]
 [ 8 11]]


In [83]:
a= np.array([1,2,5,3])
#modify existing array
a*=2
print(a)
#transpose of array
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print(a)
print(a.T)

[ 2  4 10  6]
[[1 2 3]
 [3 4 5]
 [9 6 0]]
[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [87]:
a=np.array([[1,5,6],[4,7,2],[3,1,9]])
print("Largest element is:",a.max())
print("Row-wise maximum element is:",a.max(axis=1))
print("Column-wise minimum element is:",a.min(axis=0))
print("Sum of all array element is:",a.sum())


Largest element is: 9
Row-wise maximum element is: [6 7 9]
Column-wise minimum element is: [1 1 2]
Sum of all array element is: 38


In [3]:
import numpy as np
a=np.array([[1,5,6],[4,7,2],[3,1,9]])
print("Cumulative sum:\n",a.cumsum())
print("Cumulative sum in axis 1:\n",a.cumsum(axis=1))
print("Cumulative sum in axis 0:\n",a.cumsum(axis=0))

Cumulative sum:
 [ 1  6 12 16 23 25 28 29 38]
Cumulative sum in axis 1:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
Cumulative sum in axis 0:
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


In [5]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
#add array
print("Array sum:\n",a+b)
#multiply array elementwise multiplication
print("array multiplication:\n",a*b)
#matrix multiplication
print("Matrix multiplication:\n",a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,1,3],[1,2,3],[3,2,1]])
#add array
print("Array sum:\n",a+b)
#multiply array elementwise multiplication
print("array multiplication:\n",a*b)
#matrix multiplication
print("Matrix multiplication:\n",a.dot(b))

Array sum:
 [[ 3  3  6]
 [ 5  7  9]
 [10 10 10]]
array multiplication:
 [[ 2  2  9]
 [ 4 10 18]
 [21 16  9]]
Matrix multiplication:
 [[13 11 12]
 [31 26 33]
 [49 41 54]]


In [14]:
a=np.array([[1,4,2],[3,4,6],[0,-1,5]])
#Sorted array
print(np.sort(a,axis=None))
#Sort a1 row-wise
print(np.sort(a,axis=1))
#Sort a0 clumn-wise
print(np.sort(a,axis=0))

[-1  0  1  2  3  4  4  5  6]
[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [18]:
#Decending Sort
a=np.array([[1,4,2],[3,4,6],[0,-1,5]])
#Sorted array
print(np.sort(a,axis=None)[::-1])
#Sort a1 row-wise
a=np.array([[1,4,2],[3,4,6],[0,-1,5]])
print(np.sort(a,axis=1)[::-1])
#Sort a0 clumn-wise
a=np.array([[1,4,2],[3,4,6],[0,-1,5]])
print(np.sort(a,axis=0)[::-1])

[ 6  5  4  4  3  2  1  0 -1]
[[-1  0  5]
 [ 3  4  6]
 [ 1  2  4]]
[[ 3  4  6]
 [ 1  4  5]
 [ 0 -1  2]]


In [22]:
# Stacking
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#vertical stacking
print("Vertical stacking:\n",np.vstack((a,b)))
#horizontal stacking
print("\nHorizontal stacking:\n",np.hstack((a,b)))
#column stacking
print("\nColumn stacking:\n",np.column_stack((a,b)))
#Concatenation method
print("\nConcatening to 2nd axis::\n",np.concatenate((a,b),1))
print("\nConcatening to 1nd axis::\n",np.concatenate((a,b),0))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Concatening to 2nd axis::
 [[1 2 5 6]
 [3 4 7 8]]

Concatening to 1nd axis::
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
