In [1]:
import numpy as np 
a=np.array([5,7,3,1])
b=np.array([90,50,0,30])
c=a*b
print(c)

[450 350   0  30]


In [5]:
A=np.array([[11,22,33],[10,20,30]])
print(A)
b=np.array([1,2,3])
print(b)
C=A+b
print(C)

[[11 22 33]
 [10 20 30]]
[1 2 3]
[[12 24 36]
 [11 22 33]]


In [7]:
#make a copy change the original array,and display both array
a=np.array([1,2,3,4,5])
b=a.copy()
a[0]=42
print(a)
print(b)

[42  2  3  4  5]
[1 2 3 4 5]


In [9]:
#make a copy change the original array,and display both array
a=np.array([1,2,3,4,5])
b=a.view()
a[0]=42
print(a)
print(b)

[42  2  3  4  5]
[42  2  3  4  5]


In [11]:
#make a copy change the original array,and display both array
#check the base attribute to check if an array owns it's data or not
a=np.array([1,2,3,4,5])
x=a.copy()
y=a.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [13]:
#split the array
a=np.array([1,2,3,4,5,6])
newarr=np.array_split(a,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
#split the array
a=np.array([1,2,3,4,5,6])
newarr=np.array_split(a,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [17]:
#split 2d array
#split the array
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print("Array 1\n",newarr[0])
print("Array 2\n",newarr[1])
print("Array 3\n",newarr[2])

Array 1
 [[1 2]
 [3 4]]
Array 2
 [[5 6]
 [7 8]]
Array 3
 [[ 9 10]
 [11 12]]


In [19]:
#spliting along with axis
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr0=np.array_split(a,3,axis=0)
newarr1=np.array_split(a,3,axis=1)
print(newarr0)
print(newarr1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [25]:
#spliting using hsplit(horizontal)
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
new1=np.hsplit(a,3)
print(new1)

[array([[[ 1,  2,  3]],

       [[10, 11, 12]]]), array([[[ 4,  5,  6]],

       [[13, 14, 15]]]), array([[[ 7,  8,  9]],

       [[16, 17, 18]]])]


In [27]:
#spliting using vsplit(vertical)
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
new1=np.vsplit(a,2)
print(new1)

[array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]]), array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])]


In [29]:
#spliting using dsplit(digonal)
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
new1=np.dsplit(a,3)
print(new1)

[array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18]]])]


In [33]:
#searching in array
a=np.array([1,2,3,4,5,4,4])
x=np.where(a==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [35]:
#searching in array
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [39]:
#sorted search
#searching in array
a=np.array([6,7,8,9])
x=np.searchsorted(a,7)
print(x)

1


In [41]:
#sorted search
a=np.array([6,7,8,9])
x=np.searchsorted(a,7,side='right')
print(x)

2


In [47]:
#sorted search
a=np.array([1,3,5,7])
x=np.searchsorted(a,[2,4,6])
print(x)

[1 2 3]


In [49]:
#create and save the file
a=np.array([[2,4,5],[8,10,12]])
#save the file
np.save('file1.npy',a)

In [51]:
#load and save numpy array
loaded_array=np.load('file1.npy')
#display the loaded array
print(loaded_array)

[[ 2  4  5]
 [ 8 10 12]]
